services:
  - redis

matrix:
  include:
  - rvm: 2.2.10
    gemfile: gemfiles/Gemfile.rails-3.x
  - rvm: 2.2.10
    gemfile: gemfiles/Gemfile.rails-4.x
  - rvm: 2.3.7
    gemfile: gemfiles/Gemfile.rails-5.x
  - rvm: 2.4.4
    gemfile: gemfiles/Gemfile.rails-5.x
  - rvm: 2.5.1
    gemfile: gemfiles/Gemfile.rails-5.x

cache: bundler
sudo: false